#!/bin/bash
# Reference: 
# https://www.humhub.org/docs/guide-admin-installation.html
# https://developers.openshift.com/managing-your-applications/environment-variables.html

pwd

echo "retrieving humhub stable"
cd  ${OPENSHIFT_REPO_DIR}
pwd
wget --quiet https://github.com/humhub/humhub/archive/stable.zip
unzip -q stable.zip

echo "fetch dependancies"
cd  ${OPENSHIFT_REPO_DIR}/humhub-stable/
ls
php composer.phar global require "fxp/composer-asset-plugin:~1.1.1"
php composer.phar update

echo "writable by the webserver TODO:check 777 ok"
chmod 777 ${OPENSHIFT_REPO_DIR}/humhub-stable/assets
chmod 777 ${OPENSHIFT_REPO_DIR}/humhub-stable/protected/config
chmod 777 ${OPENSHIFT_REPO_DIR}/humhub-stable/protected/modules
chmod 777 ${OPENSHIFT_REPO_DIR}/humhub-stable/protected/runtime
chmod 777 ${OPENSHIFT_REPO_DIR}/humhub-stable/uploads

echo "executable"
chmod ugo+x ${OPENSHIFT_REPO_DIR}/humhub-stable/protected/yii
chmod ugo+x ${OPENSHIFT_REPO_DIR}/humhub-stable/protected/yii.bat

echo "do not allow accessable by webserver: TODO: check that .htaccess is correct"
echo protected
echo uploads/file