#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

set -e

if [ -z $OPENSHIFT_MYSQL_DB_HOST ]
then
    echo 1>&2
    echo "Could not find mysql database.  Please run:" 1>&2
    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.4" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
    exit 5
fi

# Confirm database exists, if not create it
if ! mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" --password="$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" -e "select * from sfj8s_assets;" "$OPENSHIFT_APP_NAME" > /dev/null 2>&1
then
    echo "creating humhub database"
#    mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" --password="$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" "$OPENSHIFT_APP_NAME" <<EOF
    mysql  <<EOF
CREATE DATABASE if not exists humhub 
    DEFAULT CHARACTER SET utf8 
    DEFAULT COLLATE utf8_general_ci;
GRANT ALL 
    ON humhub.* 
    TO ${OPENSHIFT_MYSQL_DB_USERNAME}@localhost 
    IDENTIFIED BY "${OPENSHIFT_MYSQL_DB_PASSWORD}";
FLUSH PRIVILEGES;    
EOF
else
    echo "Database found, skipping import."
fi

