CREATE DATABASE if not exists `humhub` CHARACTER SET utf8 COLLATE utf8_general_ci;
$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST
GRANT ALL ON `humhub`.* TO `$OPENSHIFT_MYSQL_DB_USERNAME`@localhost IDENTIFIED BY '$OPENSHIFT_MYSQL_DB_PASSWORD';
FLUSH PRIVILEGES;